FROM python:3.11-slim

WORKDIR /app

# system deps for build/ssl
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential gcc libc-dev libssl-dev && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app
ENV PYTHONUNBUFFERED=1

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8020", "--loop", "asyncio"]
